// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luwpjzrsjuudbyhrlhhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1d3BqenJzanV1ZGJ5aHJsaGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjYzNTQsImV4cCI6MjA2MDU0MjM1NH0.uRF-JYlwOByTjo6TI2C7KaFm6SB1kdgy6fTS72lC6lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);